---
repositoryUrl: 'git@github.com:bdellegrazie/vue-hello-world.git'
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/npm":
    npmPublish: false
    tarballDir: "pack"
  - "semantic-release-ado":
    varName: "version"
    setOnlyOnRelease: true
  - "@semantic-release/github":
    assets:
      - name: "vue-hello-world-${nextRelease.gitTag}"
        label: "Vue Hello World (${nextRelease.gitTag}) distribution"
        path: "pack/*.tgz"
  - "@semantic-release/git"
preset: "conventionalcommits"
