---
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/github":
    assets:
      - name: "vue-hello-world-${nextRelease.gitTag}"
        label: "Vue Hello World (${nextRelease.gitTag}) distribution"
        path: "dist/**"
  - "@semantic-release/git"
preset: "conventionalcommits"
